### ISSUE TITLE
Strange pip bug makes installing requirements fail

### ISSUE THREAD

**Issue by domenukk** [fgsect/fexm#6]
When installing requirements from scratch in a new virtualenv, I just got the following error:
```Collecting fasttext==0.8.3 (from -r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/a4/86/ff826211bc9e28d4c371668b30b4b2c38a09127e5e73017b1c0cd52f9dfa/fasttext-0.8.3.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 25.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gvaxymum/fasttext/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'

    ----------------------------------------
```

According to other repos, this happens when Cython and othere dependencies are installed at the same time and Cython is listed in `requirements.txt` as well. 
Installing Cython first gets rid of the problem. 
It's not really our fault but we could consider simply removing Cython from the requirements.txt file since this might solve the issue...

**Comment by viniul** [comment]
I think we need to solve this by installing Cython manually in our setup.sh and removing it from the requirements.txt.
